# 一、准备工作

首先准备好用到的接口和类

1. 实体类 `Category`
2. 数据层接口 `CategoryMapper`
3. 业务层接口 `CategoryService` 及 实现类 `CategoryServiceImpl`
4. 控制层实现类 `CategoryConroller`

# 二、分页查询

参考[[二、登录功能 & 员工操作#四、员工信息分页查询|员工的分页查询]]

# 三、新增分类

参考[[二、登录功能 & 员工操作#三、新增员工|新增员工]]

# 四、删除分类

`@DeleteMapping`

注意只有当该分类下是**没有关联菜品/套餐之后才可以删除**（菜品 `Dish` 和套餐 `Setmeal` 是同等级的，它们都属于某一分类）

`CategoryController` 中调用业务层自定义的 `removeById()` 函数，里面包含了判断该分类是否包含菜品和套餐，不包含才可以删除

```java
// /service/impl/CategoryServiceImpl.java
@Service  
public class CategoryServiceImpl extends ServiceImpl<CategoryMapper, Category> implements CategoryService {  
    @Autowired  
    private DishService dishService;  
  
    @Autowired  
    private SetmealService setmealService;  
  
    @Override  
    public void removeById(Long id){  
        // 1.查询当前分类是否关联了菜品，如果关联了就抛出业务异常  
        LambdaQueryWrapper<Dish> dishLambdaQueryWrapper = new LambdaQueryWrapper<>();  
        dishLambdaQueryWrapper.eq(Dish::getCategoryId, id);  
        Long dishCount = dishService.count(dishLambdaQueryWrapper);  
        // 已关联菜品  
        if (dishCount > 0) {  
            throw new CustomException("当前分类下关联了菜品，不能删除");  
        }  
  
        // 2.查询当前分类是否关联了套餐  
        LambdaQueryWrapper<Setmeal> setmealLambdaQueryWrapper = new LambdaQueryWrapper<>();  
        setmealLambdaQueryWrapper.eq(Setmeal::getCategoryId, id);  
        Long setmealCount = setmealService.count(setmealLambdaQueryWrapper);  
        // 已关联套餐  
        if (setmealCount > 0) {  
            throw new CustomException("当前分类下关联了套餐，不能删除");  
        }  
  
        // 3.正常删除分类（能否正常删除？？）  
        super.removeById(id);  
    }  
}
```

其中自定义了业务异常类 `CustomException` 

```java
public class CustomException extends RuntimeException{  
    public CustomException(String message) {  
        super(message);  
    }  
}
```

还要将其放到全局异常处理器处理

```java
/**  
 * 删除有关联的分类的异常处理方法  
 * @param ex  
 * @return  
 */  
@Slf4j  
@RestControllerAdvice(annotations = {RestController.class, Conditional.class})  
public class GlobalExceptionHandler {
	...
	
	@ExceptionHandler(CustomException.class)  
	public Result<String> exceptionHandler(CustomException ex) { 
	    log.error(ex.getMessage());  
	    return Result.error(ex.getMessage());  
	}
}
```

# 五、修改分类

参考[[二、登录功能 & 员工操作#五、启用/禁用/编辑员工账户|编辑员工]]
